services:
  app:
    container_name: app
    build:
      context: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:11
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
